const axios = require('axios');
const Well = require('../models/Well');
const DrillingEvent = require('../models/DrillingEvent');
const RiskAlert = require('../models/RiskAlert');
const DrillingReading = require('../models/DrillingReading');
const Report = require('../models/Report');
const geminiService = require('../services/geminiService');

const AI_SERVICE_URL = process.env.AI_SERVICE_URL || 'http://localhost:8000';

// Haversine
const haversineDistance = (lat1, lon1, lat2, lon2) => {
  const R = 6371;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a = Math.sin(dLat / 2) ** 2 + Math.cos((lat1 * Math.PI) / 180) * Math.cos((lat2 * Math.PI) / 180) * Math.sin(dLon / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
};

exports.chat = async (req, res) => {
  try {
    const { message, wellId, context } = req.body;
    if (!message) return res.status(400).json({ success: false, message: 'Message is required.' });

    // Build context from DB
    let dbContext = '';
    if (wellId) {
      const well = await Well.findById(wellId);
      if (well) {
        const events = await DrillingEvent.find({ wellId: well._id, verificationStatus: 'APPROVED' });
        dbContext = `Active Well: ${well.wellName}, Depth: ${well.currentDepth}m, Formation: ${well.currentFormation}. `;
        dbContext += `Historical events: ${events.map(e => `${e.eventType} at ${e.depth}m`).join(', ')}.`;
      }
    }

    // ── 1. Try Python RAG service (fast check — 5s connect timeout) ──────────
    let ragAnswer = null;
    let ragSources = [];
    try {
      const response = await axios.post(`${AI_SERVICE_URL}/rag/chat`, {
        query: message,
        well_id: wellId,
        context: dbContext,
        session_id: req.user._id.toString(),
      }, { timeout: 8000 });
      ragAnswer = response.data.answer;
      ragSources = response.data.sources || [];
    } catch (_ragErr) {
      // Python service offline — fall through to direct Gemini
    }

    if (ragAnswer) {
      return res.json({
        success: true,
        data: {
          answer: ragAnswer,
          sources: ragSources,
          isAIGenerated: true,
          disclaimer: 'This response is generated by an AI system using verified historical drilling data. It is for decision-support purposes only and requires engineering review.',
        },
      });
    }

    // ── 2. Direct Gemini (always available when key is set) ──────────────────
    if (geminiService.isConfigured()) {
      const geminiPrompt = `${dbContext ? 'Context:\n' + dbContext + '\n\n' : ''}User question: ${message}`;
      const geminiAnswer = await geminiService.generate(geminiPrompt);
      if (geminiAnswer) {
        return res.json({
          success: true,
          data: {
            answer: geminiAnswer,
            sources: [],
            isAIGenerated: true,
            disclaimer: 'This response was generated by Gemini AI using available operational context. It is for decision-support purposes only and requires engineering review.',
          },
        });
      }
    }

    // ── 3. Deterministic keyword fallback ────────────────────────────────────
    const fallbackAnswer = await generateDeterministicAnswer(message, wellId);
    return res.json({
      success: true,
      data: {
        answer: fallbackAnswer,
        sources: [],
        isAIGenerated: false,
        disclaimer: 'AI service is currently unavailable. This response is generated from the verified knowledge database using keyword matching.',
      },
    });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Chat failed.' });
  }
};

async function generateDeterministicAnswer(message, wellId) {
  const lower = message.toLowerCase();
  let answer = '';

  if (lower.includes('mud loss') || lower.includes('lost circulation')) {
    const events = await DrillingEvent.find({ eventType: 'MUD_LOSS', verificationStatus: 'APPROVED' }).populate('wellId', 'wellName');
    if (events.length > 0) {
      const summary = events.slice(0, 3).map(e => `${e.wellId?.wellName || 'Unknown'} at ${e.depth}m (${e.formation || 'unknown formation'}): ${e.description?.substring(0, 150) || 'No description.'}`).join('\n');
      answer = `Found ${events.length} verified mud loss event(s) in the knowledge base:\n${summary}`;
    } else {
      answer = 'No verified mud loss events found in the current knowledge base.';
    }
  } else if (lower.includes('stuck pipe')) {
    const events = await DrillingEvent.find({ eventType: 'STUCK_PIPE', verificationStatus: 'APPROVED' }).populate('wellId', 'wellName');
    answer = events.length > 0 ? `Found ${events.length} stuck pipe event(s). Common depths: ${events.map(e => e.depth + 'm').join(', ')}.` : 'No verified stuck pipe events found.';
  } else if (lower.includes('risky') || lower.includes('risk') || lower.includes('dangerous')) {
    const alerts = await RiskAlert.find({ status: 'OPEN' }).populate('activeWellId', 'wellName').sort({ riskLevel: -1 }).limit(3);
    if (alerts.length > 0) {
      answer = `Current open risk alerts:\n${alerts.map(a => `${a.activeWellId?.wellName}: ${a.riskLevel} risk — ${a.reason}`).join('\n')}`;
    } else {
      answer = 'No open risk alerts currently in the system.';
    }
  } else if (lower.includes('formation')) {
    const events = await DrillingEvent.find({ verificationStatus: 'APPROVED' }).distinct('formation');
    answer = `Formations with recorded events: ${events.filter(Boolean).join(', ')}.`;
  } else {
    answer = 'I could not find sufficient verified evidence in the knowledge base to answer this specific query. Please try asking about specific event types (mud loss, stuck pipe, kick), formations, or risk levels.';
  }

  return answer;
}

exports.search = async (req, res) => {
  try {
    const { query, wellId, topK = 5 } = req.body;
    if (!query) return res.status(400).json({ success: false, message: 'Query is required.' });

    try {
      const response = await axios.post(`${AI_SERVICE_URL}/rag/search`, {
        query,
        well_id: wellId,
        top_k: parseInt(topK),
      }, { timeout: 30000 });

      return res.json({ success: true, data: response.data.results || [] });
    } catch (aiErr) {
      // Fallback: text search on events
      const events = await DrillingEvent.find({
        verificationStatus: 'APPROVED',
        $or: [
          { description: { $regex: query, $options: 'i' } },
          { mitigation: { $regex: query, $options: 'i' } },
          { formation: { $regex: query, $options: 'i' } },
          { eventType: { $regex: query.replace(/\s+/g, '_'), $options: 'i' } },
        ],
      }).populate('wellId', 'wellName field').populate('sourceDocumentId', 'title').limit(10);

      return res.json({
        success: true,
        data: events.map(e => ({
          text: e.description,
          well: e.wellId?.wellName,
          depth: e.depth,
          formation: e.formation,
          eventType: e.eventType,
          document: e.sourceDocumentId?.title,
          page: e.sourcePage,
          relevance: 0.7,
          source: 'database-keyword-search',
        })),
        fallback: true,
      });
    }
  } catch (error) {
    res.status(500).json({ success: false, message: 'Search failed.' });
  }
};

exports.analyzeReport = async (req, res) => {
  try {
    const { reportId } = req.body;
    const report = await Report.findById(reportId).populate('wellId');
    if (!report) return res.status(404).json({ success: false, message: 'Report not found.' });

    try {
      const response = await axios.post(`${AI_SERVICE_URL}/extract-report`, {
        document_id: reportId,
        text: report.rawText,
        well_name: report.wellName,
      }, { timeout: 60000 });

      res.json({ success: true, data: response.data });
    } catch (aiErr) {
      res.json({ success: true, data: { events: [], message: 'AI analysis service unavailable. Manual review required.' }, fallback: true });
    }
  } catch (error) {
    res.status(500).json({ success: false, message: 'Analysis failed.' });
  }
};

exports.compareWells = async (req, res) => {
  try {
    const { wellId1, wellId2 } = req.body;
    const [well1, well2] = await Promise.all([Well.findById(wellId1), Well.findById(wellId2)]);
    if (!well1 || !well2) return res.status(404).json({ success: false, message: 'One or both wells not found.' });

    const [events1, events2] = await Promise.all([
      DrillingEvent.find({ wellId: wellId1, verificationStatus: 'APPROVED' }).sort({ depth: 1 }),
      DrillingEvent.find({ wellId: wellId2, verificationStatus: 'APPROVED' }).sort({ depth: 1 }),
    ]);

    const [readings1, readings2] = await Promise.all([
      DrillingReading.find({ wellId: wellId1 }).sort({ depth: 1 }).limit(200),
      DrillingReading.find({ wellId: wellId2 }).sort({ depth: 1 }).limit(200),
    ]);

    const distance = haversineDistance(well1.latitude, well1.longitude, well2.latitude, well2.longitude);

    const sharedFormations = (well1.formations || [])
      .filter(f => (well2.formations || []).some(f2 => f2.name.toLowerCase() === f.name.toLowerCase()))
      .map(f => f.name);

    const commonEventTypes = [...new Set(events1.map(e => e.eventType))]
      .filter(t => events2.some(e => e.eventType === t));

    let aiSummary = '';
    try {
      const response = await axios.post(`${AI_SERVICE_URL}/rag/chat`, {
        query: `Compare drilling characteristics, historical events, and risks between ${well1.wellName} and ${well2.wellName}. Well 1 events: ${events1.map(e => e.eventType).join(', ')}. Well 2 events: ${events2.map(e => e.eventType).join(', ')}.`,
        context: `${well1.wellName} depth: ${well1.currentDepth}m, formations: ${well1.formations?.map(f => f.name).join(', ')}. ${well2.wellName} depth: ${well2.currentDepth}m, formations: ${well2.formations?.map(f => f.name).join(', ')}.`,
      }, { timeout: 30000 });
      aiSummary = response.data.answer;
    } catch {
      // Try direct Gemini before deterministic fallback
      if (geminiService.isConfigured()) {
        const prompt = `Compare drilling characteristics, historical events, and risks between ${well1.wellName} and ${well2.wellName}.\n` +
          `${well1.wellName}: depth ${well1.currentDepth}m, formations: ${well1.formations?.map(f => f.name).join(', ') || 'unknown'}, events: ${events1.map(e => e.eventType.replace(/_/g, ' ')).join(', ') || 'none'}.\n` +
          `${well2.wellName}: depth ${well2.currentDepth}m, formations: ${well2.formations?.map(f => f.name).join(', ') || 'unknown'}, events: ${events2.map(e => e.eventType.replace(/_/g, ' ')).join(', ') || 'none'}.`;
        aiSummary = await geminiService.generate(prompt) || '';
      }
      if (!aiSummary) {
        aiSummary = `${well1.wellName} has ${events1.length} recorded events. ${well2.wellName} has ${events2.length} recorded events. Both wells share ${sharedFormations.length} formation(s): ${sharedFormations.join(', ') || 'none'}. Common event types: ${commonEventTypes.map(t => t.replace(/_/g, ' ')).join(', ') || 'none'}.`;
      }
    }

    res.json({
      success: true,
      data: {
        well1: { ...well1.toObject(), events: events1, readings: readings1 },
        well2: { ...well2.toObject(), events: events2, readings: readings2 },
        comparison: { distance: parseFloat(distance.toFixed(2)), sharedFormations, commonEventTypes },
        aiSummary,
      },
    });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Comparison failed.' });
  }
};

exports.operationsSummary = async (req, res) => {
  try {
    const [activeWells, highRiskAlerts, openAlerts, recentEvents] = await Promise.all([
      Well.find({ status: 'DRILLING', isActive: true }),
      RiskAlert.find({ riskLevel: { $in: ['HIGH', 'CRITICAL'] }, status: 'OPEN' }).populate('activeWellId', 'wellName'),
      RiskAlert.countDocuments({ status: 'OPEN' }),
      DrillingEvent.find({ verificationStatus: 'APPROVED' }).sort({ createdAt: -1 }).limit(5).populate('wellId', 'wellName'),
    ]);

    let summary = '';
    try {
      const context = `Active wells: ${activeWells.map(w => `${w.wellName} at ${w.currentDepth}m (${w.riskLevel} risk)`).join(', ')}. High risk alerts: ${highRiskAlerts.map(a => `${a.activeWellId?.wellName}: ${a.reason?.substring(0, 100)}`).join('. ')}.`;
      const response = await axios.post(`${AI_SERVICE_URL}/rag/chat`, {
        query: 'Generate a concise operations briefing for drilling management based on current well status, risk alerts, and historical events.',
        context,
      }, { timeout: 30000 });
      summary = response.data.answer;
    } catch {
      // Try direct Gemini before deterministic fallback
      if (geminiService.isConfigured()) {
        const context = `Active wells: ${activeWells.map(w => `${w.wellName} at ${w.currentDepth}m (${w.riskLevel} risk)`).join(', ') || 'None'}. ` +
          `High risk alerts: ${highRiskAlerts.map(a => `${a.activeWellId?.wellName}: ${a.reason?.substring(0, 100)}`).join('. ') || 'None'}.`;
        const prompt = `Generate a concise operations briefing for drilling management.\nContext:\n${context}`;
        summary = await geminiService.generate(prompt) || '';
      }
      if (!summary) {
        // Deterministic fallback
        summary = `Operations Overview: ${activeWells.length} well(s) currently drilling. ${openAlerts} open alert(s), including ${highRiskAlerts.length} high/critical risk alert(s).`;
        if (highRiskAlerts.length > 0) {
          summary += ` Priority wells requiring attention: ${highRiskAlerts.map(a => a.activeWellId?.wellName).filter(Boolean).join(', ')}.`;
        }
        if (recentEvents.length > 0) {
          summary += ` Recent verified events: ${recentEvents.map(e => `${e.eventType.replace(/_/g, ' ')} in ${e.wellId?.wellName}`).join(', ')}.`;
        }
      }
    }

    res.json({
      success: true,
      data: {
        summary,
        metrics: {
          activeWells: activeWells.length,
          highRiskAlerts: highRiskAlerts.length,
          openAlerts,
          recentEvents: recentEvents.length,
        },
        isAIGenerated: true,
        disclaimer: 'Summary generated using available operational data. For critical decisions, consult individual well reports.',
      },
    });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Summary generation failed.' });
  }
};
